import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavbarComponent } from "./components/NavbarComponent";
import StoreProvider from "./StoreProvider";
import Providers from "./components/Providers";
import TanStaskProvider from "./components/TanStaskProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanStaskProvider>
          <Providers>
            <StoreProvider>
              <NavbarComponent />
              {children}
            </StoreProvider>
          </Providers>
        </TanStaskProvider>
      </body>
    </html>
  );
}
